### ISSUE TITLE
Build arm64 images as part of pipeline

### ISSUE THREAD

**Issue by buzzsurfr** [coder/enterprise-images#185]
Multi-arch images have been around since 2020. The `codercom/enterprise-*` images should include multi-arch support.

For example, [codercom/enterprise-base](https://hub.docker.com/r/codercom/enterprise-base/tags) only lists `linux/amd64` for OS/Arch.

**Comment by tuananh** [comment]
I'll take this if no one else is on it. Will submit a PR later this week.

**Comment by alexanderkjeldaas** [comment]
Hi, I got a failed installation on scaleway and found that the default `codercom/enterprise-base` is not a multi-arch arm64 image.  Would be great if this was fixed.

I guess the alternative now requires editing the template and building my own image, but it would be better if this was done here.

**Comment by jaulz** [comment]
@tuananh is that something we can expect soon? 😊

**Comment by tuananh** [comment]
@jaulz totally forgot about this. I opened a draft PR here https://github.com/coder/enterprise-images/pull/237
