### ISSUE TITLE
Missing python3

### ISSUE THREAD

**Issue by christopherpalm264** [coder/enterprise-images#253]
Perhaps I'm confused but when I use this latest image codercom/enterprise-base:ubuntu there's no python installed, which should be default on Ubuntu 22.04.

```
coder@58eab7a8e663:/$ python3                  
bash: python3: command not found
```

Please have a look!

Chris

**Comment by au2001** [comment]
Looks like the minimal image was incorrectly pushed to the base image repository
It got fixed a few minutes ago (#249, #250) so it's fixed now (at least on my side)

**Comment by johnstcn** [comment]
Related to https://github.com/coder/enterprise-images/pull/249
This should be fixed now. Thanks for reporting!

**Comment by matifali** [comment]
@christopherpalm264 you can use the SHA256 tag from current latest

**Comment by christopherpalm264** [comment]
Excellent thanks!
