### ISSUE TITLE
Feature-request: Versioned image tags

### ISSUE THREAD

**Issue by Jasper-Ben** [coder/enterprise-images#272]
:wave: all

As you are only providing "latest-style" tagging (i.e. all new changes will end up in "ubuntu" tag), there is currently no easy way for users to version-lock the currently used image. Would it be possible to add an additional tag with version identifier (could be something as simple as a timestamp) to container images?

**Comment by johnstcn** [comment]
@Jasper-Ben Would `ubuntu-YYYYMMDD` work as a tag?

**Comment by Jasper-Ben** [comment]
Yes, perfect 👍
