### ISSUE TITLE
How to customize user environment environment variables ?

### ISSUE THREAD

**Issue by gustavetd** [coder/enterprise-images#74]
I would like to pass down (dynamic) Secrets to my user workspaces. 

Is there a way to add custom environment variables when the workspace are created ? (or any other way to do this, with service accounts for ex.) 

Thanks !

**Comment by bpmct** [comment]
Hi @gustavetd. The ability for developers to set their own keys / environment variables when creating a workspace is planned. For now, I suggest one of these, depending on your use case:
- adding it into the image team-wide with `ENV`
- add a secrets manager to the image, such as [Doppler](https://www.doppler.com/)
- dynamically fetching a user's secrets and adding it as an environment variable in `.bashrc` via a [configure step](https://coder.com/docs/workspaces/workspaces-as-code/templates)
