### ISSUE TITLE
Support Jupyterlab as Application - current image launches Jupyter classic

### ISSUE THREAD

**Issue by grepler** [coder/enterprise-images#76]
The Jupyter launcher in the Applications pane launches jupyter, not jupyterlab. The docker build file is installing jupyterlab.

Jupyterlab is not included in the documented list of 'Applications' which don't require use of Dev URLs, but classic Jupyter works in the official image - can we expand support for Lab?
https://coder.com/docs/workspaces/editors#manually-installing-jetbrains-ides
https://coder.com/docs/admin/workspace-management/installing-jetbrains#supported-ides

![image](https://user-images.githubusercontent.com/3301065/120880951-a1cb7380-c59b-11eb-8588-60f3a914e8a3.png)

I have been able to get dev-urls working correctly, but we use Cloudflare on front of our webservers and I cannot setup wildcard subdomains, so utilizing the Application proxy at least for Jupyterlab in addition to vsCode & Pycharm would be very helpful.

**Comment by grepler** [comment]
I have just noticed the documentation regarding Cloudflare wildcard ACME using DNS01:
https://coder.com/docs/guides/ssl-certificates/cloudflare

I would still prefer to have JupyterLab as a recognized application, but I think I can make this work for the time being.

**Comment by jawnsy** [comment]
@grepler That's an excellent suggestion, thank you! I agree that JupyterLab would be nice for us to support. We're planning an overhaul of the way that we produce and publish our container images, but that is going to be a large effort and we don't have a timeline for completing this work.

In the meantime, are you able to manually start JupyterLab and connect to it using a DevURL?

**Comment by jawnsy** [comment]
@grepler That's an excellent suggestion, thank you! I agree that JupyterLab would be nice for us to support. We're planning an overhaul of the way that we produce and publish our container images, but that is going to be a large effort and we don't have a timeline for completing this work.

In the meantime, are you able to manually start JupyterLab and connect to it using a DevURL?

**Comment by grepler** [comment]
glad to hear it @jawnsy, I was initially struggling with some storage issues on my local cluster, so just now working through that Cloudflare/certmanager documentation Love this project so far!
