### ISSUE TITLE
RStudio image

### ISSUE THREAD

**Issue by greyscaled** [coder/enterprise-images#80]
Much like Jupyter, create an image for RStudio

**Comment by jawnsy** [comment]
@vapurrmaid Do we know which RStudio variant we're targeting? https://www.rstudio.com/products/rstudio/download/

Would it be RStudio Server, or do we want to support all of them?

**Comment by vapurrmaid** [comment]
RStudio Server

**Comment by matifali** [comment]
We have deprecated specialled images please see: #238
