### ISSUE TITLE
improvements to VNC image

### ISSUE THREAD

**Issue by bpmct** [coder/enterprise-images#93]
- [ ] switch log out action to shut down workspace and show a zenity prompt. (log out exits the desktop environment)
- [ ] switch to another desktop environment that is more programmable via the CLI and config files (it is not well documented, and arguably impossible to manage multiple panels via the CLI in xfce4)
- [ ] explore only starting desktop/VNC server on initial connection? will this save resources?

**Comment by matifali** [comment]
Also consider moving to Ubuntu:220.04 as base.

**Comment by matifali** [comment]
We have deprecated specialled images please see: #238
